name: 'CI'
on: [push, pull_request]
jobs:
  build:
    name: 'Builds and Compiles'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '18.x'
      - run: ./build/setup-emsdk.sh
      - run: npm ci
      - run: npm run build-onig
      - run: npm run build-wasm
      - run: npm run build-tsc
      - run: npm run package
      - run: npm test
